version: '3.8'
services:
  portainer:
    image: portainer/portainer-ce:2.18.3-alpine
    container_name: portainer
    restart: unless-stopped
    ports:
      # - 127.0.0.1:9443:9443 # https
      - 0.0.0.0:9000:9000 # http
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
  # nexus:
  #   image: sonatype/nexus3:3.52.0
  #   container_name: nexus
  #   restart: unless-stopped
  #   ports:
  #     - 127.0.0.1:8081:8081
  #     - 127.0.0.1:8085:8085
  #   volumes:
  #     - ./nexus:/nexus-data
