version: '3.8'
services:
  portainer:
    image: portainer/portainer-ce:2.20.0-alpine
    container_name: portainer
    restart: unless-stopped
    ports:
      - 0.0.0.0:9000:9000
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock